name: ecommerce_concept
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.0
  flutter_rating_bar: ^4.0.1
  carousel_slider: ^4.1.1
  # state
  provider: ^6.0.1
  get_it: ^7.2.0

  # utils
  flutter_screenutil: ^5.0.0+2
  json_annotation: ^4.4.0
  flutter_svg: ^0.23.0+1

  # remote
  retrofit: ^3.0.1
  dio: ^4.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: any
  json_serializable: ^6.1.3
  retrofit_generator: ^4.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/icons/
    


  fonts:
    - family: MarkPro
      fonts:
        - asset: assets/fonts/mark_pro.ttf
  